import type { Day } from '@/types';
import { enhanceCurriculumDay } from './curriculum-enhancer';

const rawCurriculum = [
    { day: 1, topic: 'Introduction to AI & Python', project: 'Setup Python, Anaconda, and VSCode.' },
    { day: 2, topic: 'Python Basics: Variables & Data Types', project: 'Program to calculate the area of a circle.' },
    { day: 3, topic: 'Python Strings', project: 'A simple string reversal and palindrome checker.' },
    { day: 4, topic: 'Python Lists', project: 'Todo list application using list methods.' },
    { day: 5, topic: 'Python Dictionaries and Tuples', project: 'Contact book using a dictionary.' },
    { day: 6, topic: 'Conditional Statements (if/elif/else)', project: 'A simple calculator that handles different operations.' },
    { day: 7, topic: 'Loops in Python (for/while)', project: 'Program to print multiplication tables.' },
    { day: 8, topic: 'Functions in Python', project: 'A temperature converter (Celsius to Fahrenheit and vice-versa).' },
    { day: 9, topic: 'File I/O in Python', project: 'A program that reads a text file and counts word frequency.' },
    { day: 10, topic: 'Object-Oriented Programming (OOP) - Part 1', project: 'Create a `Car` class with methods and attributes.' },
    { day: 11, topic: 'OOP - Part 2 (Inheritance, Polymorphism)', project: 'Create subclasses for different types of vehicles.' },
    { day: 12, topic: 'Introduction to NumPy', project: 'Basic array manipulations and calculations.' },
    { day: 13, topic: 'NumPy Array Operations', project: 'Image manipulation using NumPy arrays (e.g., grayscale).' },
    { day: 14, topic: 'Introduction to Pandas', project: 'Loading a CSV file into a DataFrame and basic inspection.' },
    { day: 15, topic: 'Pandas Data Selection & Filtering', project: 'Filtering a dataset based on multiple conditions.' },
    { day: 16, topic: 'Pandas Data Cleaning', project: 'Handling missing values and duplicates in a dataset.' },
    { day: 17, topic: 'Pandas GroupBy and Aggregation', project: 'Analyzing a sales dataset to find total sales per region.' },
    { day: 18, topic: 'Introduction to Matplotlib', project: 'Creating basic plots (line, bar, scatter) from a dataset.' },
    { day: 19, topic: 'Matplotlib Customization', project: 'Customizing plots with titles, labels, and colors.' },
    { day: 20, topic: 'Introduction to Seaborn', project: 'Creating statistical plots like boxplots and violin plots.' },
    { day: 21, topic: 'Seaborn for Advanced Visualization', project: 'Using pairplots and heatmaps for exploratory data analysis.' },
    { day: 22, topic: 'Introduction to Scikit-learn', project: 'Overview of the library and its main features.' },
    { day: 23, topic: 'Linear Regression - Theory', project: 'Mathematical concepts behind linear regression.' },
    { day: 24, topic: 'Linear Regression - Implementation', project: 'Predicting house prices using a simple linear regression model.' },
    { day: 25, topic: 'Logistic Regression - Theory', project: 'Understanding classification and the sigmoid function.' },
    { day: 26, topic: 'Logistic Regression - Implementation', project: 'Classifying emails as spam or not spam.' },
    { day: 27, topic: 'Decision Trees - Theory', project: 'Understanding how decision trees work.' },
    { day: 28, topic: 'Decision Trees - Implementation', project: 'Predicting customer churn using a decision tree.' },
    { day: 29, topic: 'Random Forests - Theory', project: 'Concept of ensemble learning.' },
    { day: 30, topic: 'Random Forests - Implementation', project: 'Improving the customer churn prediction model with a random forest.' },
    { day: 31, topic: 'Support Vector Machines (SVM) - Theory', project: 'Understanding hyperplanes and margins.' },
    { day: 32, topic: 'SVM - Implementation', project: 'Image classification using SVM.' },
    { day: 33, topic: 'K-Nearest Neighbors (KNN) - Theory', project: 'Understanding instance-based learning.' },
    { day: 34, topic: 'KNN - Implementation', project: 'Recommending movies based on user ratings.' },
    { day: 35, topic: 'K-Means Clustering - Theory', project: 'Understanding unsupervised learning and clustering.' },
    { day: 36, topic: 'K-Means Clustering - Implementation', project: 'Segmenting customers based on their purchasing behavior.' },
    { day: 37, topic: 'Principal Component Analysis (PCA) - Theory', project: 'Understanding dimensionality reduction.' },
    { day: 38, topic: 'PCA - Implementation', project: 'Compressing image data using PCA.' },
    { day: 39, topic: 'Model Evaluation Metrics - Classification', project: 'Accuracy, Precision, Recall, F1-score.' },
    { day: 40, topic: 'Model Evaluation Metrics - Regression', project: 'MSE, MAE, R-squared.' },
    { day: 41, topic: 'Cross-Validation and Hyperparameter Tuning', project: 'Optimizing a model using GridSearchCV.' },
    { day: 42, topic: 'Feature Engineering and Selection', project: 'Improving model performance by creating and selecting features.' },
    { day: 43, topic: 'Introduction to Neural Networks', project: 'Understanding the basic structure of a neural network.' },
    { day: 44, topic: 'Building a Simple Neural Network with Keras', project: 'A simple image classifier using Keras.' },
    { day: 45, topic: 'Introduction to TensorFlow', project: 'Understanding tensors and basic operations.' },
    { day: 46, topic: 'Building Models with TensorFlow', project: 'Re-implementing the image classifier with raw TensorFlow.' },
    { day: 47, topic: 'Introduction to PyTorch', project: 'Understanding PyTorch tensors and autograd.' },
    { day: 48, topic: 'Building Models with PyTorch', project: 'Re-implementing the image classifier with PyTorch.' },
    { day: 49, topic: 'Convolutional Neural Networks (CNNs) - Theory', project: 'Understanding convolutions and pooling layers.' },
    { day: 50, topic: 'CNNs - Implementation', project: 'Building a more advanced image classifier for CIFAR-10.' },
    { day: 51, topic: 'Recurrent Neural Networks (RNNs) - Theory', project: 'Understanding sequential data and recurrent layers.' },
    { day: 52, topic: 'RNNs - Implementation', project: 'Sentiment analysis on movie reviews.' },
    { day: 53, topic: 'Long Short-Term Memory (LSTMs)', project: 'Improving the sentiment analysis model with LSTMs.' },
    { day: 54, topic: 'Natural Language Processing (NLP) Basics', project: 'Tokenization, stemming, and lemmatization.' },
    { day: 55, topic: 'Word Embeddings (Word2Vec, GloVe)', project: 'Visualizing word embeddings.' },
    { day: 56, topic: 'Introduction to Transformers', project: 'Understanding the attention mechanism.' },
    { day: 57, topic: 'Building with Transformers (e.g., BERT)', project: 'Fine-tuning a pre-trained BERT model for a specific task.' },
    { day: 58, topic: 'Introduction to Generative AI', project: 'Understanding GANs and VAEs.' },
    { day: 59, topic: 'Generative Adversarial Networks (GANs)', project: 'Generating handwritten digits with a simple GAN.' },
    { day: 60, topic: 'Introduction to Reinforcement Learning', project: 'Understanding agents, environments, and rewards.' },
    { day: 61, topic: 'Q-Learning', project: 'Solving a simple grid-world problem with Q-learning.' },
    { day: 62, topic: 'Deep Q-Networks (DQNs)', project: 'Playing a simple Atari game with a DQN.' },
    { day: 63, topic: 'Introduction to MLOps', project: 'Understanding the lifecycle of a machine learning project.' },
    { day: 64, topic: 'Model Deployment with Flask', project: 'Creating a REST API for a trained model.' },
    { day: 65, topic: 'Docker for Machine Learning', project: 'Containerizing the Flask API.' },
    { day: 66, topic: 'Introduction to Cloud AI Platforms (GCP)', project: 'Overview of Google AI Platform.' },
    { day: 67, topic: 'Introduction to Cloud AI Platforms (AWS)', project: 'Overview of Amazon SageMaker.' },
    { day: 68, topic: 'Introduction to Cloud AI Platforms (Azure)', project: 'Overview of Azure Machine Learning.' },
    { day: 69, topic: 'SQL for Data Science - Part 1', project: 'Basic queries, filtering, and sorting.' },
    { day: 70, topic: 'SQL for Data Science - Part 2', project: 'Joins, aggregation, and subqueries.' },
    { day: 71, topic: 'Advanced Python: Decorators', project: 'Creating custom decorators.' },
    { day: 72, topic: 'Advanced Python: Generators', project: 'Working with large datasets efficiently.' },
    { day: 73, topic: 'Advanced Python: Concurrency', project: 'Using threading and multiprocessing.' },
    { day: 74, topic: 'Web Scraping with BeautifulSoup and Scrapy', project: 'Scraping data from a website.' },
    { day: 75, topic: 'Time Series Analysis', project: 'Forecasting stock prices.' },
    { day: 76, topic: 'Anomaly Detection', project: 'Detecting fraudulent transactions.' },
    { day: 77, topic: 'Recommender Systems', project: 'Building a content-based recommender system.' },
    { day: 78, topic: 'Computer Vision with OpenCV', project: 'Basic image processing and object detection.' },
    { day: 79, topic: 'Advanced NLP: Topic Modeling', project: 'Using LDA to identify topics in a corpus of text.' },
    { day: 80, topic: 'Explainable AI (XAI)', project: 'Using SHAP and LIME to interpret model predictions.' },
    { day: 81, topic: 'Ethical AI', project: 'Understanding and mitigating bias in AI models.' },
    { day: 82, topic: 'Introduction to Big Data with Spark', project: 'Understanding RDDs and DataFrames.' },
    { day: 83, topic: 'Data Manipulation with PySpark', project: 'Performing data transformations on a large dataset.' },
    { day: 84, topic: 'Machine Learning with MLlib', project: 'Training a model on a distributed dataset.' },
    { day: 85, topic: 'Graph Neural Networks (GNNs)', project: 'Node classification in a social network.' },
    { day: 86, topic: 'Federated Learning', project: 'Training a model on decentralized data.' },
    { day: 87, topic: 'AutoML with TPOT', project: 'Automating the machine learning pipeline.' },
    { day: 88, topic: 'Introduction to Genkit', project: 'Creating a simple AI flow.' },
    { day: 89, topic: 'Building RAG systems with Genkit', project: 'Creating a retrieval-augmented generation system.' },
    { day: 90, topic: 'Capstone Project - Part 1: Ideation', project: 'Define a real-world problem to solve with AI.' },
    { day: 91, topic: 'Capstone Project - Part 2: Data Collection', project: 'Gather and preprocess data for the project.' },
    { day: 92, topic: 'Capstone Project - Part 3: Model Building', project: 'Train and evaluate a machine learning model.' },
    { day: 93, topic: 'Capstone Project - Part 4: API Development', project: 'Create an API to serve the model.' },
    { day: 94, topic: 'Capstone Project - Part 5: Frontend', project: 'Build a simple UI to interact with the model.' },
    { day: 95, topic: 'Capstone Project - Part 6: Deployment', project: 'Deploy the full-stack application.' },
    { day: 96, topic: 'Preparing for Interviews: Data Structures', project: 'Reviewing common data structures.' },
    { day: 97, topic: 'Preparing for Interviews: Algorithms', project: 'Solving common algorithm problems (e.g., LeetCode).' },
    { day: 98, topic: 'Preparing for Interviews: System Design', project: 'Designing a large-scale AI system.' },
    { day: 99, topic: 'Preparing for Interviews: ML Concepts', project: 'Reviewing key machine learning concepts.' },
    { day: 100, topic: 'Continuous Learning and Future Trends', project: 'Exploring new papers and technologies in AI.' },
    { day: 101, topic: 'Advanced SQL: Window Functions', project: 'Rankings and moving averages.' },
    { day: 102, topic: 'Advanced SQL: Common Table Expressions (CTEs)', project: 'Complex query organization.' },
    { day: 103, topic: 'NoSQL Databases: MongoDB', project: 'CRUD operations in MongoDB.' },
    { day: 104, topic: 'Advanced Pandas: Multi-indexing', project: 'Hierarchical data analysis.' },
    { day: 105, topic: 'Advanced Pandas: Time Series Resampling', project: 'Working with different time granularities.' },
    { day: 106, topic: 'Data Visualization with Plotly', project: 'Creating interactive plots.' },
    { day: 107, topic: 'Data Visualization with Altair', project: 'Declarative statistical visualization.' },
    { day: 108, topic: 'Model Interpretability with SHAP', project: 'Explaining model predictions.' },
    { day: 109, topic: 'Model Interpretability with LIME', project: 'Local interpretable model-agnostic explanations.' },
    { day: 110, topic: 'Bias and Fairness in AI', project: 'Auditing a model for fairness.' },
    { day: 111, topic: 'Causal Inference - Theory', project: 'Correlation vs. causation.' },
    { day: 112, topic: 'Causal Inference - Implementation', project: 'Using DoWhy and EconML.' },
    { day: 113, topic: 'Bayesian Inference - Theory', project: 'Introduction to Bayesian thinking.' },
    { day: 114, topic: 'Bayesian Inference - PyMC3', project: 'Building a Bayesian regression model.' },
    { day: 115, topic: 'Gaussian Processes', project: 'Bayesian approach to regression.' },
    { day: 116, topic: 'Transfer Learning in NLP', project: 'Fine-tuning GPT-3 for text generation.' },
    { day: 117, topic: 'Transfer Learning in Computer Vision', project: 'Fine-tuning a pre-trained CNN.' },
    { day: 118, topic: 'Self-Supervised Learning', project: 'Learning representations from unlabeled data.' },
    { day: 119, topic: 'Meta-Learning', project: 'Learning to learn.' },
    { day: 120, topic: 'Quantum Machine Learning - Theory', project: 'Introduction to quantum computing for ML.' },
    { day: 121, topic: 'Quantum Machine Learning - Implementation', project: 'Using TensorFlow Quantum.' },
    { day: 122, topic: 'MLOps: CI/CD for ML', project: 'Automating model training and deployment.' },
    { day: 123, topic: 'MLOps: Model Monitoring', project: 'Tracking model performance in production.' },
    { day: 124, topic: 'MLOps: Data Versioning (DVC)', project: 'Managing data and models like code.' },
    { day: 125, topic: 'Advanced Git for Data Science', project: 'Branching strategies and collaboration.' },
    { day: 126, topic: 'Reproducible Research', project: 'Creating reproducible ML experiments.' },
    { day: 127, topic: 'Building a Data Science Portfolio', project: 'Showcasing your skills.' },
    { day: 128, topic: 'Communicating Data Science Results', project: 'Storytelling with data.' },
    { day: 129, topic: 'Ethics in Data Collection', project: 'Privacy and consent.' },
    { day: 130, topic: 'Advanced Deep Learning Architectures', project: 'Exploring ResNet, Inception, etc.' },
    { day: 131, topic: 'Object Detection with YOLO', project: 'Real-time object detection.' },
    { day: 132, topic: 'Image Segmentation with U-Net', project: 'Semantic segmentation of images.' },
    { day: 133, topic: 'Neural Style Transfer', project: 'Combining content and style of images.' },
    { day: 134, topic: 'Speech Recognition', project: 'Building a simple speech-to-text model.' },
    { day: 135, topic: 'Music Generation with AI', project: 'Generating MIDI music with RNNs.' },
    { day: 136, topic: 'Deep Reinforcement Learning in Practice', project: 'Policy Gradients and A3C.' },
    { day: 137, topic: 'AI in Finance: Algorithmic Trading', project: 'Backtesting a simple trading strategy.' },
    { day: 138, topic: 'AI in Healthcare: Medical Imaging', project: 'Classifying medical images.' },
    { day: 139, topic: 'AI in E-commerce: Personalization', project: 'Building a personalized recommendation engine.' },
    { day: 140, topic: 'AI for Social Good', project: 'Using AI to address societal challenges.' },
    { day: 141, topic: 'Advanced Web Scraping', project: 'Handling JavaScript-heavy sites with Selenium.' },
    { day: 142, topic: 'Working with APIs', project: 'Integrating external data sources.' },
    { day: 143, topic: 'Building a Data Dashboard with Dash', project: 'Interactive data visualization.' },
    { day: 144, topic: 'Building a Data Dashboard with Streamlit', project: 'Creating data apps with Python.' },
    { day: 145, topic: 'Scaling Python with Dask', project: 'Parallel computing for analytics.' },
    { day: 146, topic: 'High-Performance Python with Numba', project: 'Speeding up Python code.' },
    { day: 147, topic: 'Functional Programming in Python', project: 'Map, filter, reduce, and lambdas.' },
    { day: 148, topic: 'Python Best Practices (PEP 8)', project: 'Writing clean and readable code.' },
    { day: 149, topic: 'Testing and Debugging in Python', project: 'Unit testing with pytest.' },
    { day: 150, topic: 'Mid-point Review and Project Showcase', project: 'Present a mini-project.' },
    { day: 151, topic: 'Graph Databases (Neo4j)', project: 'Modeling and querying graph data.' },
    { day: 152, topic: 'Time-series Databases (InfluxDB)', project: 'Storing and querying time-series data.' },
    { day: 153, topic: 'Data Warehousing Concepts (BigQuery/Snowflake)', project: 'Understanding modern data warehouses.' },
    { day: 154, topic: 'Data Engineering Pipelines with Airflow', project: 'Orchestrating data workflows.' },
    { day: 155, topic: 'Streaming Data with Kafka', project: 'Real-time data processing.' },
    { day: 156, topic: 'Feature Stores', project: 'Managing features for ML models.' },
    { day: 157, topic: 'Advanced CNNs: Attention in Vision', project: 'Vision Transformer (ViT).' },
    { day: 158, topic: 'Generative Models: Variational Autoencoders (VAEs)', project: 'Generating images with VAEs.' },
    { day: 159, topic: 'Generative Models: Normalizing Flows', project: 'Tractable density estimation.' },
    { day: 160, topic: 'Generative Models: Diffusion Models', project: 'Generating high-quality images.' },
    { day: 161, topic: 'Advanced NLP: Text Summarization', project: 'Extractive and abstractive summarization.' },
    { day: 162, topic: 'Advanced NLP: Question Answering', project: 'Building a QA system.' },
    { day: 163, topic: 'Advanced NLP: Machine Translation', project: 'Building a neural machine translation model.' },
    { day: 164, topic: 'Unsupervised NLP: Document Clustering', project: 'Grouping similar documents.' },
    { day: 165, topic: 'Few-Shot Learning', project: 'Training models with minimal data.' },
    { day: 166, topic: 'Zero-Shot Learning', project: 'Recognizing classes unseen during training.' },
    { day: 167, topic: 'Continual Learning', project: 'Training models on a continuous stream of data.' },
    { day: 168, topic: 'Adversarial Attacks and Defenses', project: 'Making models more robust.' },
    { day: 169, topic: 'Differential Privacy', project: 'Training models with privacy guarantees.' },
    { day: 170, topic: 'Homomorphic Encryption', project: 'Computing on encrypted data.' },
    { day: 171, topic: 'Multi-modal Learning', project: 'Combining text, image, and audio data.' },
    { day: 172, topic: 'AI and Robotics', project: 'Controlling a robot with reinforcement learning.' },
    { day: 173, topic: 'Creative AI: Art and Music', project: 'Generating creative content.' },
    { day: 174, topic: 'AI in Gaming', project: 'Creating intelligent NPCs.' },
    { day: 175, topic: 'AI for Climate Change', project: 'Modeling and prediction for environmental science.' },
    { day: 176, topic: 'The Business of AI', project: 'Developing a business case for an AI project.' },
    { day: 177, topic: 'Presenting to Stakeholders', project: 'Effectively communicating technical results.' },
    { day: 178, topic: 'Reading AI Research Papers', project: 'How to stay up-to-date with the latest research.' },
    { day: 179, topic: 'Contributing to Open Source', project: 'Getting involved in the AI community.' },
    { day: 180, topic: 'Project: Build a Full AI Application', project: 'Putting all the pieces together.' },
    { day: 181, topic: 'Advanced Time Series: ARIMA/SARIMA', project: 'Statistical time series forecasting.' },
    { day: 182, topic: 'Advanced Time Series: Prophet', project: 'Forecasting with Facebook\'s Prophet.' },
    { day: 183, topic: 'Advanced Time Series: LSTMs for Forecasting', project: 'Deep learning for time series.' },
    { day: 184, topic: 'Geospatial Data Analysis', project: 'Working with maps and location data.' },
    { day: 185, topic: 'Network Analysis with NetworkX', project: 'Analyzing social and other networks.' },
    { day: 186, topic: 'Survival Analysis', project: 'Modeling time-to-event data.' },
    { day: 187, topic: 'Optimization with SciPy', project: 'Solving optimization problems.' },
    { day: 188, topic: 'Symbolic Mathematics with SymPy', project: 'Performing symbolic computations.' },
    { day: 189, topic: 'Introduction to JAX', project: 'High-performance machine learning research.' },
    { day: 190, topic: 'Deep Learning on Graphs with PyTorch Geometric', project: 'GNNs in practice.' },
    { day: 191, topic: 'AI in Drug Discovery', project: 'Predicting molecular properties.' },
    { day: 192, topic: 'AI in Agriculture', project: 'Crop monitoring and yield prediction.' },
    { day: 193, topic: 'Building Your Personal Brand as a Data Scientist', project: 'Blogging, social media, and networking.' },
    { day: 194, topic: 'Preparing for Technical Interviews - Mock Interview', project: 'Practice a full technical interview.' },
    { day: 195, topic: 'Preparing for Behavioral Interviews', project: 'Answering common behavioral questions.' },
    { day: 196, topic: 'Salary Negotiation for Data Scientists', project: 'Getting the compensation you deserve.' },
    { day: 197, topic: 'Choosing a Specialization in AI', project: 'Finding your niche.' },
    { day: 198, topic: 'Lifelong Learning Strategies', project: 'Staying current in a fast-moving field.' },
    { day: 199, topic: 'Final Capstone Project Presentation', project: 'Showcase your 300-day journey.' },
    { day: 200, topic: 'Wrapping up and Next Steps', project: 'Planning your future career path.' },
    { day: 201, topic: 'Advanced Python: Metaclasses', project: 'Dynamic class creation.' },
    { day: 202, topic: 'Advanced Python: Context Managers', project: 'Using the `with` statement.' },
    { day: 203, topic: 'Data Validation with Pydantic', project: 'Ensuring data quality.' },
    { day: 204, topic: 'FastAPI for High-Performance APIs', project: 'Building async web services.' },
    { day: 205, topic: 'Serverless ML with AWS Lambda', project: 'Deploying models without managing servers.' },
    { day: 206, topic: 'Serverless ML with Google Cloud Functions', project: 'Event-driven ML.' },
    { day: 207, topic: 'Kubernetes for ML (Kubeflow)', project: 'Orchestrating ML pipelines on Kubernetes.' },
    { day: 208, topic: 'Ray for Distributed Python', project: 'Scaling Python applications.' },
    { day: 209, topic: 'Building Chatbots with Rasa', project: 'Conversational AI from scratch.' },
    { day: 210, topic: 'Prompt Engineering for LLMs', project: 'Getting the most out of large language models.' },
    { day: 211, topic: 'Fine-tuning LLMs with LoRA', project: 'Efficiently adapting large models.' },
    { day: 212, topic: 'AI for Code (Copilot, etc.)', project: 'Using AI to write better code, faster.' },
    { day: 213, topic: 'AI and Art: StyleGAN and VQ-GAN', project: 'Generating high-resolution art.' },
    { day: 214, topic: 'AI in Education', project: 'Personalized learning and automated grading.' },
    { day: 215, topic: 'AI in Legal Tech', project: 'Document analysis and legal research.' },
    { day: 216, topic: 'The Future of Work with AI', project: 'How AI is changing industries.' },
    { day: 217, topic: 'Data Science in the Real World: Case Studies', project: 'Learning from successful projects.' },
    { day: 218, topic: 'A/B Testing and Experimental Design', project: 'Running and analyzing experiments.' },
    { day: 219, topic: 'Uplift Modeling', project: 'Measuring the causal effect of an action.' },
    { day: 220, topic: 'Imbalanced Data in Classification', project: 'Techniques for handling class imbalance.' },
    { day: 221, topic: 'Multi-label Classification', project: 'Predicting multiple labels for an instance.' },
    { day: 222, topic: 'Ensemble Methods: Stacking and Blending', project: 'Combining models for better performance.' },
    { day: 223, topic: 'Gradient Boosting: XGBoost', project: 'The "king" of Kaggle competitions.' },
    { day: 224, topic: 'Gradient Boosting: LightGBM', project: 'A faster and more efficient alternative.' },
    { day: 225, topic: 'Gradient Boosting: CatBoost', project: 'Handling categorical features automatically.' },
    { day: 226, topic: 'Automated Feature Engineering', project: 'Using libraries like Featuretools.' },
    { day: 227, topic: 'SQL for Advanced Analytics', project: 'User funnels and cohort analysis.' },
    { day: 228, topic: 'Data Privacy and Security', project: 'Protecting user data.' },
    { day: 229, topic: 'Model Governance and Compliance', project: 'Ensuring models meet regulatory requirements.' },
    { day: 230, topic: 'The AI Startup Ecosystem', project: 'From idea to funding.' },
    { day: 231, topic: 'Deep Dive: Attention Mechanism', project: 'The core of Transformers.' },
    { day: 232, topic: 'Deep Dive: BERT Architecture', project: 'Understanding the inner workings of BERT.' },
    { day: 233, topic: 'Deep Dive: GPT Architecture', project: 'How generative pre-trained transformers work.' },
    { day: 234, topic: 'Deep Dive: GAN Architectures', project: 'DCGAN, WGAN, etc.' },
    { day: 235, topic: 'Deep Dive: VAEs vs. GANs', project: 'Choosing the right generative model.' },
    { day: 236, topic: 'Deep Dive: Reinforcement Learning Algorithms', project: 'TRPO, PPO, etc.' },
    { day: 237, topic: 'AI Consulting as a Career Path', project: 'Solving business problems with AI.' },
    { day: 238, topic: 'Becoming an AI Researcher', project: 'A path to a PhD and beyond.' },
    { day: 239, topic: 'AI Product Management', project: 'Defining and launching AI products.' },
    { day: 240, topic: 'Mental Health and Well-being in Tech', project: 'Avoiding burnout.' },
    { day: 241, topic: 'Advanced Computer Vision: 3D Vision', project: 'Working with 3D data.' },
    { day: 242, topic: 'Advanced Computer Vision: Video Analysis', project: 'Action recognition and video summarization.' },
    { day: 243, topic: 'Advanced NLP: Low-Resource Languages', project: 'Building NLP models for less-resourced languages.' },
    { day: 244, topic: 'Advanced NLP: Conversational AI Design', project: 'Creating natural and engaging conversations.' },
    { day: 245, topic: 'AI for Accessibility', project: 'Using AI to help people with disabilities.' },
    { day: 246, topic: 'The Hardware behind AI', project: 'GPUs, TPUs, and the future of AI hardware.' },
    { day: 247, topic: 'Edge AI', project: 'Running AI models on low-power devices.' },
    { day: 248, topic: 'AI and the Metaverse', project: 'The intersection of AI and virtual worlds.' },
    { day: 249, topic: 'The Philosophy of AI', project: 'Consciousness, intelligence, and the nature of mind.' },
    { day: 250, topic: 'Final Project Ideation (Part 2)', project: 'Refining your capstone project idea.' },
    { day: 251, topic: 'Data Storytelling Workshop', project: 'Crafting compelling narratives with data.' },
    { day: 252, topic: 'Advanced Visualization Workshop', project: 'Creating complex and beautiful visualizations.' },
    { day: 253, topic: 'ML System Design Workshop', project: 'Designing a real-world ML system.' },
    { day: 254, topic: 'Code Review for Data Scientists', project: 'Giving and receiving feedback on code.' },
    { day: 255, topic: 'Working in Agile/Scrum for Data Science', project: 'Adapting agile methodologies to DS projects.' },
    { day: 256, topic: 'Building a Strong Online Presence', project: 'LinkedIn, GitHub, and personal websites.' },
    { day: 257, topic: 'Networking for Data Scientists', project: 'Making connections in the industry.' },
    { day: 258, topic: 'The State of AI - 2024 Edition', project: 'A review of the latest trends and breakthroughs.' },
    { day: 259, topic: 'The Future of AI - Predictions for 2025 and Beyond', project: 'Speculating on what\'s to come.' },
    { day: 260, topic: 'Project Check-in and Peer Feedback', project: 'Getting feedback on your final project.' },
    { day: 261, topic: 'Scientific Writing for AI Researchers', project: 'Publishing your work.' },
    { day: 262, topic: 'AI and Law', project: 'Legal implications of AI.' },
    { day: 263, topic: 'AI and Psychology', project: 'Understanding human behavior with AI.' },
    { day: 264, topic: 'AI and Economics', project: 'AI\'s impact on the economy.' },
    { day: 265, topic: 'AI and Art History', project: 'Analyzing art with AI.' },
    { day: 266, topic: 'AI and Music Composition', project: 'Composing music with AI tools.' },
    { day: 267, topic: 'AI and Film', project: 'AI in screenwriting, special effects, and more.' },
    { day: 268, topic: 'AI and Fashion', project: 'Personalized styling and trend forecasting.' },
    { day: 269, topic: 'AI and Sports Analytics', project: 'Optimizing team performance and player scouting.' },
    { day: 270, topic: 'AI and Space Exploration', project: 'Analyzing astronomical data and controlling rovers.' },
    { day: 271, topic: 'AI for Personal Productivity', project: 'Using AI to manage your time and tasks.' },
    { day: 272, topic: 'The Ethics of AGI', project: 'The moral considerations of superintelligence.' },
    { day: 273, topic: 'The Alignment Problem', project: 'Ensuring AIs do what we want them to do.' },
    { day: 274, topic: 'The Future of Human-AI Collaboration', project: 'How we will work with AIs in the future.' },
    { day: 275, topic: 'The Role of the Data Scientist in 2030', project: 'How the role will evolve.' },
    { day: 276, topic: 'Building a Career Moat', project: 'Developing unique skills and experiences.' },
    { day: 277, topic: 'The Data Scientist as an Entrepreneur', project: 'Starting your own AI-powered business.' },
    { day: 278, topic: 'The Data Scientist as a Teacher', project: 'Sharing your knowledge with others.' },
    { day: 279, topic: 'The Data Scientist as an Artist', project: 'Using data and AI as a creative medium.' },
    { day: 280, topic: 'Final Project - Last Push', project: 'Putting the finishing touches on your project.' },
    { day: 281, topic: 'Deep Dive: Optimizers in Deep Learning', project: 'Adam, RMSprop, etc.' },
    { day: 282, topic: 'Deep Dive: Activation Functions', project: 'ReLU, Leaky ReLU, etc.' },
    { day: 283, topic: 'Deep Dive: Regularization Techniques', project: 'Dropout, L1/L2, etc.' },
    { day: 284, topic: 'Deep Dive: Batch Normalization', project: 'Improving training stability.' },
    { day: 285, topic: 'Deep Dive: Transfer Learning in Practice', project: 'Tips and tricks for effective transfer learning.' },
    { day: 286, topic: 'Deep Dive: Model Compression', project: 'Making models smaller and faster.' },
    { day: 287, topic: 'Deep Dive: Quantization', project: 'Running models with lower precision.' },
    { day: 288, topic: 'Deep Dive: Pruning', project: 'Removing unnecessary connections in a neural network.' },
    { day: 289, topic: 'Deep Dive: Knowledge Distillation', project: 'Training a smaller model from a larger one.' },
    { day: 290, topic: 'Deep Dive: The Modern AI Stack', project: 'The tools and technologies that power AI today.' },
    { day: 291, topic: 'Special Topics: AI in Quantum Physics', project: 'Unlocking the secrets of the universe with AI.' },
    { day: 292, topic: 'Special Topics: AI in Material Science', project: 'Discovering new materials with AI.' },
    { day: 293, topic: 'Special Topics: AI in Personalized Medicine', project: 'Tailoring treatments to individuals.' },
    { day: 294, topic: 'Special Topics: AI in Climate Modeling', project: 'Improving our understanding of climate change.' },
    { day: 295, topic: 'Special Topics: AI for Wildlife Conservation', project: 'Protecting endangered species.' },
    { day: 296, topic: 'Special Topics: AI and the Future of Democracy', project: 'The role of AI in civic discourse.' },
    { day: 297, topic: 'Special Topics: The Future of AI Regulation', project: 'Balancing innovation and safety.' },
    { day: 298, topic: 'Special Topics: The Future of AI Education', project: 'How we will learn about AI in the future.' },
    { day: 299, topic: 'Final Review and Celebration', project: 'Reflecting on your 300-day journey.' },
    { day: 300, topic: 'Launch Day!', project: 'Share your journey and final project with the world!' }
];


export const initialCurriculum: Day[] = rawCurriculum.map((item) => {
  const enhanced = enhanceCurriculumDay(item.day, item.topic, item.project);
  
  const dayData: Day = {
    day: item.day,
    topic: item.topic,
    project: item.project,
    difficulty: enhanced.difficulty,
    estimatedHours: enhanced.estimatedHours,
    why: enhanced.why,
    realWorld: enhanced.realWorld,
    path: enhanced.path,
    tasks: [
      { id: `${item.day}-1`, title: `Study topic: ${item.topic}`, isCompleted: false },
      { id: `${item.day}-2`, title: `Complete project: ${item.project}`, isCompleted: false },
      { id: `${item.day}-3`, title: 'Review notes from previous day', isCompleted: false },
    ],
    resources: [
      {
        id: `${item.day}-r1`,
        title: `Official Python Docs for: ${item.topic.split(' ')[0]}`,
        url: `https://www.google.com/search?q=${encodeURIComponent(item.topic)}`,
        isFavorited: false,
        isCompleted: false,
      },
      {
        id: `${item.day}-r2`,
        title: `Tutorial video on ${item.project}`,
        url: `https://www.youtube.com/results?search_query=${encodeURIComponent(item.project)}`,
        isFavorited: false,
        isCompleted: false,
      },
    ],
    notes: `### Notes for Day ${item.day}\n\n*This is a great place to write down your thoughts and code snippets for **${item.topic}**.*\n\n\`\`\`python\n# Your code here\nprint("Hello, Day ${item.day}!")\n\`\`\``,
  };
  
  return dayData;
});
